# Robot parameters 
tcp_speed: 0.05

# Gripper parameters
tcp2fingertip: 0.28 #0.275 # distance from tcp to gripper fingertip
opening_per_count: 0.00065 # gripper stroke opening per rPr count
finger_thickness: 0.0072 #0.0072
max_opening: 0.1523 # max stroke of gripper excluding finger thickness
gripper_speed: 0.1 # value between 0.013 and 0.100
gripper_force: 10 # value between 0 and 100
gripper_offset: 0.004 #0.0075 #gripper postion offset for compensating the error
# finger:65, thumb: 65
# Object dimension
object_thickness: 0.0045 #0.006 # object thickness in meters
object_length: 0.023 #0.073 object length in meters

# Initial configuration
delta_0: 0.021 #delta A:0.8 #0.05 distance from fingertip to object tip within gripper
theta_0: 35.0 #40 #Angle between object and hole prior to regrasping

# Intermediate configuration
psi_regrasp: 40.11 #34,42 #Angle between object and upper finger after regrasping
theta_tilt: 20 #11,13,20 #Angle to tilt after regrasping
tuck: 10
tuck_dist: 0.008 #distance from fingertip to contact B before tuck

# Action axis

axis: [-1, 0, 0]

# Simulation
sim: 0

#object:
#silicon pad finger t:0.007, l:0.065, delta:0.03, theta_tilt:35
#Long 3dp finger with pad: t:0.0075, l:0.1055 delta:0.08
